runtime: custom
env: flex
service: customer-management-frontend
manual_scaling:
  instances: 1
network:
  instance_tag: customer-management-frontend
  name: default
  session_affinity: true
  forwarded_ports:
    - 8080:80