runtime: custom
env: flex
service: customer-core
manual_scaling:
  instances: 1
network:
  instance_tag: customer-core
  name: lakeside-mutual
  session_affinity: true
  forwarded_ports:
    - 8110:8110